Use single quotes instead of double quotes
Using double quotes here inadvertantly broke the surrounding double
quotes, opening up the possibility of globbing and word splitting.

This fixes shellcheck 'SC2027: The surrounding quotes actually unquote
this. Remove or escape them.'

diff --git a/omnavi b/omnavi
--- a/omnavi
+++ b/omnavi
@@ -125,6 +125,6 @@ if [ "$get" ]; then
 elif [ "$file" = "-" ] || [ -f "$file" ]; then
 	output
 else
-	>&2 echo "Error: "$file" does not exist."
+	>&2 echo "Error: '$file' does not exist."
 	exit 1
 fi
