Add -h, -f, -d options

diff --git a/omnavi b/omnavi
--- a/omnavi
+++ b/omnavi
@@ -20,13 +20,16 @@
 # A formatted description of the videos that were uploaded in the past day will
 # be outputted.
 
-yesterday="$(date +%s --date=yesterday)"
+output() {
 
-while read feed; do
-	# Must declare variable at this scope because of how while loops and
-	# subshells are handled.
-	info=""
-	while read line && read uploadtime; do
+	# Exit if date is invalid
+	compdate="$(date +%s --date="$date")" || exit
+
+	cat "$file" | while read feed; do
+		# Must declare variable at this scope because of how while loops and
+		# subshells are handled.
+		info=""
+		while read line && read uploadtime; do
 
 		# The first line is the name of input is the channel.
 		[ -z "$info" ] && info="│$line:\n"
@@ -34,8 +37,8 @@ while read feed; do
 		# Convert the upload timestamps to epoch time.
 		uploadtime="$(date +%s -d "$uploadtime")"
 
-		# Only print video info if the video was uploaded since yesterday.
-		if [ "$uploadtime" -gt "$yesterday" ]; then
+		# Only print video info if the video was uploaded since $compdate.
+		if [ "$uploadtime" -gt "$compdate" ]; then
 			while read title && read dur && read id; do
 				# Nicely format information about the video.
 				# Format time from seconds to [hh:mm:ss]. The 'sed' at the end
@@ -54,4 +57,45 @@ while read feed; do
 			# than one line long.
 			[ "$(printf "$info" | wc -l)" -gt 1 ] && printf "$info\n"
 		done
+}
 
+usage() {
+	cat <<- EOF
+		omnavi - A program to receive YouTube subscriptions without a Google account.
+		Copyright (C) 2020 Sebastian LaVine <mail@smlavine.com>
+		
+		This program is free software: you can redistribute it and/or modify
+		it under the terms of the GNU General Public License as published by
+		the Free Software Foundation, either version 3 of the License, or
+		(at your option) any later version.
+		
+		This program is distributed in the hope that it will be useful,
+		but WITHOUT ANY WARRANTY; without even the implied warranty of
+		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
+		GNU General Public License for more details.
+		
+		You should have received a copy of the GNU General Public License
+		along with this program. If not, see http://www.gnu.org/licenses/.
+
+		Usage: $(basename $0) [-h] [-f file] [-d date]
+		Options:
+		    -h          Prints this help.
+		    -f file     Instead of reading from stdin, reads from this file.
+		    -d date     Instead of comparing against 24 hours ago,
+		                compares against this date.
+		Examples:
+		
+	EOF
+}
+
+file="-"
+date="yesterday"
+while getopts "hf:d:" o; do
+	case "$o" in
+		f) file="$OPTARG" ;;
+		d) date="$OPTARG" ;;
+		*) usage && exit ;;
+	esac
+done
+[ "$file" = "-" -o -f "$file" ] && output ||
+	echo "Error: "$file" does not exist." >/dev/stderr && exit
